import { useState } from 'react';
import Head from 'next/head'
import styles from '../styles/Home.module.css'

import Alert from '@mui/material/Alert';
import Button from '@mui/material/Button';


export default function Home() {

  const [clickData, setClickData] = useState('');

  const callBackend = async () => {
    const resp = await fetch("http://localhost:8000/data");
    console.log("resp:", resp);
    const data = await resp.json();
    console.log("data:", JSON.stringify(data));
    setClickData(JSON.stringify(data));
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Next FastAPI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta charset="UTF-8" />
      </Head>

      <main className={styles.main}>

        <h1 className={styles.title}>
          NextJS+FastAPI testing &#x1f635;
        </h1>

        <div className={styles.grid}>

          <div className={styles.card}>
            <Button
              variant="contained"
              onClick={callBackend}
            >
              Click me!
            </Button>

            <Alert
              severity="info"
              style={{ margin: "1rem" }}
            >
              {clickData}
            </Alert>
          </div>

        </div>

      </main>

    </div>
  )
}
